name: "Set Issue Label"
on:
  issues:
    types: [opened]

jobs:
  CMake-Build:
    runs-on: windows-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["@CMake", "@build"]'
          labels: '["CMake/Build"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  Critical:
    runs-on: windows-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["@Critical"]'
          labels: '["Critical"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  Cleanup:
    runs-on: windows-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["@Cleanup"]'
          labels: '["Cleanup"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  Testing:
    runs-on: windows-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["@Testing"]'
          labels: '["Testing"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  Feature:
    runs-on: windows-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["@Feature","@Improvement"]'
          labels: '["Feature/Improvement"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  Opcode:
    runs-on: windows-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["@Opcode"]'
          labels: '["Opcodes"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"