name: "Set Issue Label"
on:
  issues:
    types: [opened]

jobs:
  CMake-Build:
    runs-on: windows-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["@CMake", "@build"]'
          labels: '["CMake/Build"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  Critical:
    runs-on: windows-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["@Critical"]'
          labels: '["Critical"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  Cleanup:
    runs-on: windows-latest
    steps:
      - uses: Naturalclar/issue-action@v1.0.0
        with:
          keywords: '["@Cleanup"]'
          labels: '["Cleanup"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
